### ISSUE TITLE
Project DB (mobile): teaser formatting broken

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#603] opened 2023-11-08 20:36 UTC
![IMG_5192](https://github.com/CorrelAid/correlaid_website/assets/67161972/2592d33e-d78f-4ead-8ff2-495e72027dc9)

**Comment by jstet** [comment] 2023-11-08 20:56
@friep i cant reproduce it. now that pagination was added, do you still experience this issue?

**Comment by jstet** [comment] 2023-11-18 22:35
wrong branch, this is still open

**Comment by friep** [comment] 2023-11-30 12:19
still persists on my iphone xs. maybe we can verify what happens on other iphones? if it's just my model, we can just close this.

**Comment by friep** [comment] 2023-11-30 12:20
still persists on my iphone xs. maybe we can verify what happens on other iphones? if it's just my model, we can just close this.

**Comment by KonradUdoHannes** [comment] 2023-11-30 14:49
I'm not able to reproduce it in edge or firefox, when I adjust the view port to the size of an iphone XS. So I think its not a general viewport issue. @friep have you tried it in a different browser on the same phone by any chance? Just to check whether something browser specific might be going on.
Also if it is browser specific rather than phone model specific it should have a higher priority for fixing I think.

**Comment by friep** [comment] 2023-12-05 10:23
@KonradUdoHannes same on chrome and firefox.

**Comment by friep** [comment] 2023-12-05 10:30
I think it has something to do with how the summary is formatted and written in directus. there are two <p> tags for some projects (didn't crosscheck with whether those are the affected projects on my phone but  likely) and i think that messes with the automatic "shortening" function?

**Comment by helen-kl** [comment] 2023-12-05 12:37
I'm getting the incorrect display in Safari and Chrome on Iphone 8, but only for the two entries "Analyse einer Mitgliederbefragung des Pfadfinderbunds Nord" and "Data Flow von R zu Metabase zu Google Docs: Ein Live-Connected Reporting-Workflow"

**Comment by KonradUdoHannes** [comment] 2023-12-10 16:41
@friep I think you might be right that the nested html tags are the problem. This seems to be a limitation of `line-clamp` css functionality wrt. some browsers, see https://github.com/tailwindlabs/tailwindcss/issues/10994
It's also in line with a quick inspection that I did for a few teasers compared to the two broken ones mentioned by @helen-kl. So far the broken ones are the only ones with nested html tags that I saw.

I'm slightly confused why it worked for @friep in firefox, but maybe there is a slight difference depending on whether the firefox instance runs on an iOS or not. In that spirit I also tried to reproduce the issue with an iphone 13 with no success, which means its should not be caused by the iOS version as both the xs and the 13 should run on the latest iOS version (as opposed to the iphone 8) see https://en.wikipedia.org/wiki/IPhone#Models.

I think generally we have two choices for fixing this.
1. Adjust the affected projects such that they don't contain nested html tags
2. Programmatically remove the nested tags for the purpose of displaying the project summaries. The assumption here is, that after all the tags are removed, `line-clamp` works as expected. There are some tradeoffs however, such as the case of removing ordered lists.

**Comment by jstet** [comment] 2023-12-13 22:46
Alrighty thanks y'all for taking a look. I will start to fix this right away

**Comment by jstet** [comment] 2023-12-13 23:23
My solution for now is to adjust the affected projects as @KonradUdoHannes suggested. 

I don't get what you mean with nested html tags however. As the summary field in directus is a html field, every summary should contain at least  <p> tags. "Data Flow von R zu Metabase zu Google Docs: Ein Live-Connected Reporting-Workflow" and  "Analyse einer Mitgliederbefragung des Pfadfinderbunds Nord" contained more than that and I have now removed the additional tags.

Could you kindly confirm if this fixed it: @friep or @helen-kl ? 

However, I see an issue with the summary field in general. It should be called teaser instead and not be a html field. It's comparable to the teaser of blog articles. It should be only a few sentences and not contain html. I opened another issue for this: https://github.com/CorrelAid/correlaid_website/issues/621

**Comment by jstet** [comment] 2023-12-13 23:25
> I think it has something to do with how the summary is formatted and written in directus. there are two
> 
> tags for some projects (didn't crosscheck with whether those are the affected projects on my phone but likely) and i think that messes with the automatic "shortening" function?

A I see now that the \<p> you wrote was invisible because of markdown

**Closed** 2024-02-09 13:24 UTC
