### ISSUE TITLE
CD fails "Error: page.waitForURL: Navigation failed because page was closed!"

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#461] opened 2023-06-02 11:50 UTC
Cant reproduce this locally. 
The only stuff i found so far:
- https://github.com/microsoft/playwright/issues/15691
- https://stackoverflow.com/questions/76086251/how-to-catch-the-new-correct-ulr-after-payment-gate-redirection-in-playwright

**Comment by jstet** [comment] 2023-06-02 11:50
I deployed the page manually because cd failed

**Comment by jstet** [comment] 2023-06-02 11:55
@KonradUdoHannes any ideas?

**Comment by KonradUdoHannes** [comment] 2023-06-06 10:16
I addressed one test (test lc chapter pages) that was particularly flake  as part of #464 . Not sure whether it addresses this issue. The flaky test was reproducable locally, but if the problem is a race condition this might have been highly sensitive to current computational load on the machine running the test.

@jstet Do you remember (can look up) whether it was the "test lc chapter pages"  test that was causing the trouble. If so we could now confidently continue and see whether the problem appears again. If it was another testcase it might make sense to investigate more right away.

**Comment by KonradUdoHannes** [comment] 2023-06-07 08:38
I see. So basically it failed for a commit for which it already passed successfully when I merged. This seems to suggest that its really a bit problematic with regard to the flakiness. I'll have a look at the situations that caused trouble to see whether we can improve it.

**Comment by KonradUdoHannes** [comment] 2023-06-07 11:00
@jstet The current failure is reproducable locally and test failure is justified (i.e. the purpouse of our test) as there seems to be an actual problem that I'll address in #466. We should pick continue with this issue after the bugs are resolved.

**Comment by KonradUdoHannes** [comment] 2023-06-07 15:29
#466 was resolved and I suggest keeping this issue open for a little bit ( maybe a few days) and closing it if no other immediate issues with the CD pipeline arise.

**Closed** 2023-06-12 07:01 UTC
Labels: Priority
