### ISSUE TITLE
Only one project shown on LC pages

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#526] opened 2023-07-12 14:24 UTC
Only one project is shown on a given LC page even if they have done more. Example:
https://www.correlaid.org/community/correlaidx/hamburg/ should have two (Trinkbrunnen in addition to the one displayed).

**Comment by KonradUdoHannes** [comment] 2023-07-12 23:58
I cannot reproduce the bug so far. I see both projects in local dynamic and static deployments. I'll check again in production tomorrow once the next daily automated update goes through. Afterwards we should be able to tell whether there is some quite subtle bug in the production configuration or whether something something in the cms might have been configured differently during the last build.

**Comment by KonradUdoHannes** [comment] 2023-07-13 03:21
Tonight's automated build succeeded and both Projects are now visible on the lc page. With this I'll close the issue as it currently seems more likely to have been an issue on the cms side. Feel free to reopen if it happens again.

**Closed by KonradUdoHannes** 2023-07-13 03:21 UTC
Labels: bug
